-language: python		
 -		
 -python:		
 -  - "2.7"		
 -		
 -install:		
 -        pip install keras		
 -        		
 -script:		
 -    - cd tests		
 -    - python example_test.py		
 -    - sonar-scanner 		
 -#Branches to build		
 -branches:		
 -        - master		
 -        - dev		
 -		
 -dist: trusty		
 -sudo: required		
 -		
 -addons:		
 -  sonarcloud:		
 -    organization: "mukz95-github"		
 -    token:		
 -      secure: "sonar"		
 -jdk:		
 -  - oraclejdk8		
 -cache:		
 -  directories:		
 -    - '$HOME/.sonar/cache'
