-language: python		

python:		
   - "2.7"		
   
install:		
      pip install keras		
        		
script:		
  - cd tests		
  - python example_test.py				
#Branches to build		
branches:		
     - master		
     - dev		

