language: python

python:
  - "2.7"

install:
        pip install keras
        
script:
    - cd tests
    - python example_test.py
    - sonar-scanner
    
addons:
        sonarcloud:
                organization: "Mukz95"
                 token: 
                        secure: sonar
#Branches to build
branches:
        - master
        - dev

